# 应用程序配置
app:
  base_url: "https://automationexercise.com"
  title: "Automation Exercise"

# 浏览器配置
browser:
  default: "chrome"
  headless: false
  window_size: "1920,1080"
  page_load_timeout: 30
  implicit_wait: 10
  explicit_wait: 15

# 支持的浏览器
browsers:
  chrome:
    binary_path: ""
    options:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
      - "--disable-gpu"
      - "--disable-extensions"
      - "--disable-logging"
      - "--disable-web-security"
      - "--allow-running-insecure-content"
  firefox:
    binary_path: ""
    options:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"
  edge:
    binary_path: ""
    options:
      - "--no-sandbox"
      - "--disable-dev-shm-usage"

# 测试数据配置
test_data:
  users_file: "data/users.json"
  products_file: "data/products.json"
  test_data_file: "data/test_data.xlsx"

# 报告配置
reports:
  allure_results: "reports/allure-results"
  allure_reports: "reports/allure-reports"
  html_reports: "reports/html"
  screenshots: "reports/screenshots"
  logs: "reports/logs"

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file: "reports/logs/automation.log"
  rotation: "10 MB"
  retention: "30 days"

# 重试配置
retry:
  max_attempts: 3
  delay: 1

# 并行执行配置
parallel:
  workers: 2
  dist: "loadfile"
